export const VERITY_CONTENT = {
  company: {
    name: "Verity Tech Co., Ltd.",
    shortName: "Verity Tech",
    domain: "www.veritytech.co.th",
    facebook: "https://www.facebook.com/veritytech.thailand",
    role: "IT Consultant, IT Solution, Digital Signage Solutions",
    taglineBrand: "INNOVATE • BUILD • ELEVATE",
  },
  taglines: {
    welcome: "Welcome to Verity Tech",
    hero: "We provide a one-stop service of Hardware and Software Development Services. Empower your business, leading your organization to the future based on your business plan.",
    swiftlet: "Swiftlet enables your innovation dreams into reality!",
    oneStop: "At Verity Tech, we're your one-stop shop for all your digital needs.",
    pushing: "Pushing Past Limits",
  },
  nav: [
    { label: "Solutions", href: "#industries" },
    { label: "Hardware", href: "#hardware", children: [
      { label: "Smart Office/Home", href: "#hardware" },
      { label: "Digital Signage", href: "#hardware" },
    ]},
    { label: "Software", href: "#software", children: [
      { label: "Custom Development", href: "#software" },
      { label: "Data & Analytics", href: "#software" },
    ]},
    { label: "About", href: "#about" },
    { label: "Blog", href: "#blog" },
    { label: "Contact", href: "#contact" },
  ],
  gateway: {
    pathTitle: "I am a…",
    pathSubtitle: "Choose your path to see how Verity Tech supports your role.",
    roles: [
      { id: "owner", label: "Business Owner", summary: "One-stop digital transformation", href: "#contact", icon: "chart" },
      { id: "it", label: "IT Manager", summary: "Hardware, software & integration", href: "#software", icon: "code" },
      { id: "facilities", label: "Facilities Manager", summary: "Smart office & digital signage", href: "#hardware", icon: "home" },
      { id: "developer", label: "Developer", summary: "Swiftlet custom development", href: "#software", icon: "display" },
    ],
    industriesTitle: "Solutions by Industry",
    industriesSubtitle: "Tailored hardware and software for your sector — from corporate offices to hospitality.",
    industries: [
      {
        id: "corporate",
        label: "Corporate Office",
        title: "Smart Office & Collaboration",
        description: "Increase productivity with wireless presentation, smart meeting rooms, interactive whiteboards, and digital signage across your workspace.",
        image: "hardware.smartHomeNeon",
        bullets: ["Smart Meeting Room", "Wireless Presentation", "MeetingMinder Room Signs", "Choros Space Booking", "Office Video Solutions"],
        href: "#hardware",
      },
      {
        id: "hospitality",
        label: "Hospitality",
        title: "Hotel & Venue Technology",
        description: "Engage guests with hotel video solutions, digital menu boards, and dynamic lobby displays managed from a central platform.",
        image: "hardware.signageMockup",
        bullets: ["Hotel Video Solutions", "Digital Menu Board", "LED/LCD Displays", "Videowall Controller", "AxisTV Signage Suite"],
        href: "#hardware",
      },
      {
        id: "retail",
        label: "Retail",
        title: "Retail Digital Signage",
        description: "Capture attention with smart digital signage, interactive displays, and content management for stores and franchises.",
        image: "hardware.signageStreet",
        bullets: ["Smart Digital Signage", "LED/LCD Displays", "Interactive Packages", "Content Management", "Multi-location scheduling"],
        href: "#hardware",
      },
      {
        id: "residential",
        label: "Residential",
        title: "Smart Home & Safety",
        description: "Take Care smart home uses AI and Line Application for safety monitoring, sensors, and emergency help for people you care about.",
        image: "hardware.homeAutomation",
        bullets: ["Take Care AI Safety", "Home Automation", "Security & Wellness", "Lighting & Entertainment", "Line Application alerts"],
        href: "#hardware",
      },
      {
        id: "enterprise",
        label: "Enterprise IT",
        title: "Custom Software & Data",
        description: "Custom web and mobile apps, data lakes, business intelligence, and system integration aligned to your business plan.",
        image: "software.phone1",
        bullets: ["Custom Development", "Data Analytics", "Cloud Data Platform", "System Integration", "DevOps & Security"],
        href: "#software",
      },
    ],
    trust: [
      { value: "HW+SW", label: "One-Stop Shop" },
      { value: "NDA", label: "Trusted Clients" },
      { value: "TH", label: "Thailand HQ" },
      { value: "Swiftlet", label: "Innovation Platform" },
    ],
  },
  compare: {
    label: "Solutions",
    title: "Hardware, software, or both?",
    subtitle: "Most engagements combine both pillars — pick where you want to start.",
    columns: [
      {
        id: "hardware",
        title: "Hardware Solutions",
        href: "#hardware",
        highlights: [
          "Digital Signage & LED/LCD",
          "Smart Office / Smart Home",
          "Videowall Controllers (4K)",
          "AxisTV & Visix Suite",
          "Take Care AI Safety",
        ],
        cta: "Explore Hardware",
      },
      {
        id: "software",
        title: "Software Solutions",
        href: "#software",
        highlights: [
          "Custom Web & Mobile Apps",
          "Data Lakes & BI",
          "Cloud Data Platform",
          "System Integration",
          "DevOps & Security",
        ],
        cta: "Explore Software",
      },
    ],
  },
  unicorn: {
    enabled: false,
    projectId: "",
  },
  process: {
    label: "How We Work",
    title: "From plan to production",
    subtitle: "One accountable partner through every phase of your digital journey.",
    steps: [
      { num: "01", title: "Consult", icon: "chart", body: "Align on your business plan, scope hardware and software needs, and map the path forward." },
      { num: "02", title: "Design", icon: "display", body: "Architecture, UX/UI, and integration plans tailored to your workspace and workflows." },
      { num: "03", title: "Build", icon: "code", body: "Custom development, signage systems, and platform engineering with industry-standard stacks." },
      { num: "04", title: "Deploy", icon: "layers", body: "Installation, configuration, and go-live for digital signage, smart office, and software." },
      { num: "05", title: "Support", icon: "headset", body: "Local Thailand support by phone, email, and Line from a team you can reach." },
    ],
  },
  capabilities: {
    label: "Why Verity Tech",
    title: "One partner, end to end",
    subtitle: "From the screen on the wall to the platform behind it — hardware and software under one roof.",
    tiles: [
      { icon: "layers", title: "One-stop hardware + software", body: "Skip the integrator shuffle. We design, build, and support both the devices and the software that runs them — accountable end to end.", feature: true },
      { icon: "cube", title: "Swiftlet platform", body: "Our in-house innovation platform turns ideas into working products faster." },
      { icon: "signal", title: "Digital signage at scale", body: "AxisTV, videowall controllers and LED/LCD managed from one place." },
      { icon: "chart", title: "Data-driven decisions", body: "Data lakes, BI and analytics that turn raw data into action." },
      { icon: "shield", title: "Security & compliance", body: "360° security reviews aligned to government regulations." },
      { icon: "headset", title: "Local Thailand support", body: "A team you can reach by phone, email or Line — in your timezone." },
    ],
  },
  faq: {
    label: "FAQ",
    title: "Questions, answered",
    subtitle: "The essentials before you reach out.",
    items: [
      { q: "What does Verity Tech do?", a: "We're a one-stop hardware and software development partner. That spans digital signage and smart office/home hardware, plus custom software, mobile apps, and data analytics — built around your business plan." },
      { q: "Can you build custom software?", a: "Yes. We deliver custom web and mobile apps, system architecture, UX/UI, testing automation, and DevOps. We work in industry-standard frameworks including React, AngularJS, and Python." },
      { q: "What digital signage products do you provide?", a: "Smart digital signage, LED/LCD displays, 4K videowall controllers (HDMI/DVI/VGA), digital menu boards, and the AxisTV Signage Suite for cloud content management, scheduling, and room signs." },
      { q: "Do you offer data consulting and analytics?", a: "Yes. We build cloud data platforms, data lakes/lakehouses, warehouses, BI and visualization, and advanced analytics — with data governance and customer-insight services." },
      { q: "How do we get started?", a: "Send a message through the contact form, or reach our team directly by phone, email, or Line. We'll scope your needs and propose a hardware and/or software path." },
    ],
  },
  services: [
    {
      num: "001",
      name: "Data Consulting",
      icon: "chart",
      summary: "Data Analytics, Data Governance, Customer Insights",
      href: "#software",
    },
    {
      num: "002",
      name: "Software Solutions",
      icon: "code",
      summary: "Custom Web, Mobile App, System Integration",
      href: "#software",
    },
    {
      num: "003",
      name: "Smart Office & Home",
      icon: "home",
      summary: "Wireless Presentation, Smart Lighting, Security Devices",
      href: "#hardware",
    },
    {
      num: "004",
      name: "Digital Signage",
      icon: "display",
      summary: "LED/LCD Displays, Videowall Controller, Digital Menu Board",
      href: "#hardware",
    },
  ],
  hardware: {
    title: "Hardware Products",
    subtitle: "Unlocking the Possibilities of Digital Signage and Smart Office/Home Solutions",
    intro: "For both hardware and software solutions — click or scroll below to learn more.",
    categories: [
      {
        name: "Smart Office/Home",
        image: "smartOffice",
        description: "Our Smart Office & Home solution provides an integrated technology platform that can help you to increase productivity and efficiency in your workspace. It offers a suite of hardware and software solutions that can help you to streamline processes, automate tasks, and enhance communication with colleagues and clients.",
        items: [
          "Smart Meeting Room", "Interactive Whiteboard", "Conferencing Devices",
          "Presentation Devices", "Home Theater", "Home Entertainment",
          "MeetingMinder Touch & E-Paper Room Signs", "Choros Space Booking",
          "Take Care Smart Home — AI safety monitoring via Line Application",
        ],
        subcategories: [
          { name: "Home Automation", image: "homeAutomation" },
          { name: "Security and Wellness", image: "safetyWellness" },
          { name: "Lighting and Entertainment", image: "lighting" },
        ],
      },
      {
        name: "Digital Signage",
        image: "signageMockup",
        description: "Our Digital Signage solution is an interactive and dynamic content display system that can be tailored to your specific needs. With its customizable displays, you can quickly and easily create and manage content for large or small audiences.",
        items: [
          "Smart Digital Signage", "LED/LCD Displays", "Smart Video Controller",
          "Digital Menu Board", "Hotel Video Solutions", "Office Video Solutions",
          "Videowall Controller (4K, HDMI/DVI/VGA)", "AxisTV Signage Suite",
          "Digital Signage Software & Hardware",
        ],
        products: [
          {
            name: "Videowall Controller",
            image: "videowall",
            description: "Manage high-resolution video walls with an intuitive interface. Multi-format inputs (HDMI, DVI, VGA), up to 4K resolution, built-in scalers for perfect image fit.",
          },
          {
            name: "LED/LCD Displays",
            image: "lcd",
            description: "Superior image quality, long-lasting performance and easy integration. Our team helps you choose the best display and ensures smooth installation.",
          },
        ],
      },
    ],
    visix: {
      title: "Visix Digital Signage Products",
      intro: "Download the Visix catalog for an overview of Visix products and services: AxisTV Signage Suite software, interactive designs, digital room signs and more.",
      products: [
        { name: "AxisTV Signage Suite", description: "Cloud-based content management with 100+ media sources, smart playlists, flexible scheduling and multi-user licenses." },
        { name: "Interactive Packages", description: "Affordable touchscreen design packages built from award-winning templates." },
        { name: "Choros Space Booking", description: "Book spaces from your smartphone — no app download or website login required." },
        { name: "MeetingMinder Touch Room Signs", description: "Show room schedules from your calendar or book a room at the touchscreen sign." },
        { name: "MeetingMinder Connect Room Signs", description: "Stand-alone room management without AxisTV content management software." },
        { name: "MeetingMinder EPS E-Paper Signs", description: "Affordable wireless room and desk signs for conference rooms, hot desking and hybrid offices." },
      ],
    },
    takeCare: {
      title: "Take Care Smart Home",
      description: "The innovation that started using AI to check safety under the brand \"Take Care\" follows the people you care about. Smart Home acts as a set of sensors and a help button in case of emergency, including an AI system that helps analyze camera image data. Closed circuit alarm system via Line Application.",
      image: "homeAutomation",
    },
  },
  software: {
    title: "Software Solutions",
    subtitle: "Experience the Power of Verity Tech: Professional Software Development & Data-driven Solutions",
    categories: [
      {
        name: "Software Development",
        image: "phone1",
        description: "At Verity Tech Co. Ltd., we believe that every business is unique. That's why we offer customized solutions tailored to your specific needs and goals. Our team of experts works closely with you to ensure that our solutions meet your expectations and exceed your goals.",
        items: [
          "Custom Development", "Mobile App Development", "Web App Development",
          "Architecture Design", "UX/UI Design", "Testing Automation",
          "DevOps/Platform Engineering", "Security and Audit Compliance",
          "Off-the-Shelf Product Implementation",
        ],
        stacks: "React, AngularJS, Python",
      },
      {
        name: "Data-Driven Solutions",
        image: "phone2",
        description: "At Verity Tech Co. Ltd., we believe that data is the key to success. That's why we offer data consulting and analytics services that help businesses make informed, data-driven decisions.",
        items: [
          "Cloud Data Platform", "Data Lake & Data Lakehouse", "Data Warehouse",
          "Business Intelligence & Data Visualization", "Advanced Data Analytics",
          "Data Integration & Data Replication", "Data Virtualization",
          "Data Management & Data Catalog", "Customer Insights", "Data Governance",
          "Digital Transformation",
        ],
      },
    ],
    development: {
      title: "Custom Software Solutions",
      intro: "Our custom web solutions are tailored to meet your unique business needs.",
      features: [
        { name: "Custom Web / Mobile Development", icon: "code", description: "Tailored to your unique business needs. We specialize in industry-standard frameworks including React, AngularJS, Python, and more." },
        { name: "Custom Architecture Systems", icon: "display", description: "Scalable high-performance enterprise systems and modular platforms. We understand your needs, then design and implement a platform that meets them." },
        { name: "Off-the-Shelf Implementation", icon: "home", description: "A team of certified professionals helps you choose the right software, implement it successfully, and offers support services to get the most out of it." },
        { name: "Security & Audit Compliance", icon: "chart", description: "Industry-leading security from secure payment processing to secure systems. We comply with government regulations and provide a 360-degree security review." },
      ],
    },
    data: {
      title: "Data Consulting & Analytics",
      intro: "A team of data experts, engineers, and analysts passionate about using data and insight to solve real-world business problems.",
      features: [
        { name: "Customer Insights", icon: "chart", description: "Understand and anticipate every customer's needs. We use the latest technology to extract behavior and purchase patterns so you reach customers more effectively." },
        { name: "Data Governance", icon: "display", description: "Ensuring the right data is in the right place at the right time. Our experienced team builds robust data governance and strategy to maximize efficiency and minimize risk." },
        { name: "Data Analytics", icon: "code", description: "Advanced analytics that turn raw data into actionable insight, helping you make informed, data-driven decisions across the organization." },
        { name: "Digital Transformation", icon: "home", description: "Modernize processes and platforms end-to-end, aligning data and technology with your long-term business plan." },
      ],
    },
    techStacks: {
      title: "Technology Stacks",
      frontend: ["React", "AngularJS", "Vue", "TypeScript"],
      backend: ["Python", "Node.js", "Java", "REST / GraphQL"],
      mobile: ["React Native", "Flutter", "Swift", "Kotlin"],
      data: ["Cloud Data Platform", "Data Lakehouse", "BI & Visualization", "ETL / ELT"],
    },
  },
  about: {
    title: "Our Story",
    image: "team",
    body: "Verity Tech Co. Ltd. was founded on the belief that businesses can push past their limits with innovative technology solutions. Our team of experts is dedicated to engineering fresh solutions that solve complex problems and enable businesses to achieve their full potential.",
    experience: "With years of experience from our veteran team members in consultation and execution we have had many clients and projects. A lot of them are under a Non-disclosure agreement. Here are a few examples that we can publicly disclose.",
    partners: {
      title: "Our Partners & Technology",
      note: "We integrate leading signage, collaboration, and development platforms.",
      carousel: [
        "Visix", "AxisTV", "MeetingMinder", "Choros", "Take Care",
        "React", "AngularJS", "Python", "Swiftlet", "Verity Tech",
      ],
    },
  },
  blog: {
    title: "Blogs",
    posts: [{
      title: "The most recent advancements in IT and technology for 2023 - ความก้าวหน้าในด้านเทคโนโลยีในปี 2023",
      author: "autta bb",
      date: "Nov 27, 2023",
      image: "blog2023",
      excerpt: "ปี 2023 เป็นอีกปีที่นวัตกรรมและเทคโนโลยีก้าวหน้าไปอีกขั้น Blog นี้ทางเรารวบรวมหัวข้อการพัฒนาทางด้านนวัตกรรมที่น่าสนใจจากทั่วโลก",
      body: "ปี 2023 เป็นอีกปีที่นวัตกรรมและเทคโนโลยีก้าวหน้าไปอีกขั้น Blog นี้ทางเรารวบรวมหัวข้อการพัฒนาทางด้านนวัตกรรมที่น่าสนใจจากทั่วโลก ตั้งแต่ AI และ Machine Learning ไปจนถึง Cloud Computing และ Cybersecurity เพื่อให้ธุรกิจของคุณพร้อมรับมือกับการเปลี่ยนแปลง",
      lang: "th",
    }],
  },
  contact: {
    title: "Contact",
    cta: "Contact Sales",
    description: "Ready to empower your business? Reach out for hardware and software solutions.",
    // Set to a Formspree (or similar) endpoint to enable real delivery.
    // Empty string = mailto fallback. See .env.example CONTACT_FORM_ENDPOINT.
    endpoint: "",
    person: {
      name: "Sasi Nanthaphiriyakit",
      title: "Founder & CEO",
      phone: "+66 81 234 5678",
      email: "sasi@veritytech.co.th",
      line: "sasiwork",
    },
  },
  footer: {
    copyright: "© Verity Tech Co., Ltd.",
  },
};
